// The Decoy documentation site — decoy.nerdmenot.in
//
// Starlight owns `src/content/docs/**` and nothing else. The landing page and the
// story pages are plain Astro routes with their own layout, because a docs framework's
// default shell is the fastest way to make a project look like every other project.
// What Starlight is here for is the part it genuinely does better than a bespoke build:
// sidebar, search, keyboard nav, heading anchors and a11y on the reference pages.
import { defineConfig } from 'astro/config'
import starlight from '@astrojs/starlight'
import starlightVersions from 'starlight-versions'

export default defineConfig({
  site: 'https://decoy.nerdmenot.in',
  integrations: [
    starlight({
      title: 'Decoy',
      description:
        'Seeded fake data for Swift, with provenance. Every value traces to a licensed, ' +
        'pinned source — and where it cannot, the corpus says so rather than guessing.',
      logo: { src: './src/assets/icon.svg', alt: 'Decoy', replacesTitle: false },
      favicon: '/icon.svg',
      customCss: ['./src/styles/theme.css'],
      // Code reads as a terminal in both site themes. A light syntax theme on warm paper
      // washes out to near-invisible, and switching themes mid-scroll is worse than
      // committing to one.
      expressiveCode: {
        themes: ['github-dark'],
        styleOverrides: {
          borderRadius: '3px',
          borderColor: 'transparent',
          codeFontFamily: 'var(--decoy-mono)',
        },
      },
      plugins: [
        starlightVersions({
          // Labelled with the release it documents rather than "Latest", so the control
          // names a version somebody can actually put in `from:`.
          current: { label: 'v1.1.x' },
          // One entry per MINOR series, not per tag. Under semver a patch cannot change
          // the API, so a patch's docs are its minor's — archiving each tag would publish
          // near-duplicates. And a published URL is permanent: once `/1-0/` exists and
          // somebody links it, removing it breaks their link, so archive at the coarsest
          // granularity that is still useful.
          //
          // `1-0` is a snapshot of a tree that no longer exists and nothing regenerates
          // it. `bun run extract` therefore writes only the directories it owns.
          versions: [{ slug: '1-0', label: 'v1.0.x' }],
        }),
      ],
      components: {
        // The two loudest Starlight tells: its header lockup and its theme dropdown.
        //
        // A component override here beats a plugin's, so Header and PageTitle have to
        // render the versions plugin's own components themselves — the switcher, the
        // version-scoped search and the outdated-version notice. Drop those and they
        // disappear with no error, which is the failure mode worth knowing about.
        Header: './src/components/Header.astro',
        PageTitle: './src/components/PageTitle.astro',
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/nerdmenot-swift/decoy' },
      ],
      editLink: { baseUrl: 'https://github.com/nerdmenot-swift/decoy/edit/main/website/' },
      lastUpdated: true,
      pagination: true,
      head: [
        { tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' } },
        {
          tag: 'link',
          attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true },
        },
        {
          tag: 'link',
          attrs: {
            rel: 'stylesheet',
            href:
              'https://fonts.googleapis.com/css2?' +
              'family=Public+Sans:wght@400;500;600;700&' +
              'family=IBM+Plex+Mono:wght@400;500;600&display=swap',
          },
        },
        // Applied before first paint, so a reader who collapsed the table of contents
        // does not watch it flash open on every navigation.
        {
          tag: 'script',
          content:
            "try{if(localStorage.getItem('decoy:toc'))" +
            "document.documentElement.dataset.toc='collapsed'}catch(e){}",
        },
      ],
      sidebar: [
        {
          label: 'Start',
          items: [
            { slug: 'start/install' },
            { slug: 'start/quick-start' },
            { slug: 'start/cheatsheet' },
          ],
        },
        {
          label: 'Guides',
          items: [
            { slug: 'guides/forges' },
            { slug: 'guides/testing' },
            { slug: 'guides/seeding-a-database' },
            { slug: 'guides/locales' },
            { slug: 'guides/seeds' },
          ],
        },
        {
          // Autogenerated so a new namespace appears without touching this file.
          label: 'Generators',
          // Twenty-nine entries, which is most of the sidebar if left open. Starlight
          // expands whichever group holds the current page, so landing on a namespace
          // still shows its siblings.
          collapsed: true,
          items: [{ autogenerate: { directory: 'api' } }],
        },
        {
          label: 'Reference',
          items: [
            { slug: 'reference/locale-matrix' },
            { slug: 'reference/sources' },
            { slug: 'reference/cli' },
            { slug: 'reference/corpus-format' },
            { slug: 'reference/design-notes' },
          ],
        },
      ],
    }),
  ],
})
