// The Decoy documentation site — decoy.nerdmenot.in
//
// Starlight owns `src/content/docs/**` and nothing else. The landing page and the
// story pages are plain Astro routes with their own layout, because a docs framework's
// default shell is the fastest way to make a project look like every other project.
// What Starlight is here for is the part it genuinely does better than a bespoke build:
// sidebar, search, keyboard nav, heading anchors and a11y on the reference pages.
import { defineConfig } from 'astro/config'
import starlight from '@astrojs/starlight'

export default defineConfig({
  site: 'https://decoy.nerdmenot.in',
  integrations: [
    starlight({
      title: 'Decoy',
      description:
        'Seeded fake data for Swift, with provenance. Every value traces to a licensed, ' +
        'pinned source — and where it cannot, the corpus says so rather than guessing.',
      logo: { src: './src/assets/icon.svg', alt: 'Decoy', replacesTitle: false },
      favicon: '/icon.svg',
      customCss: ['./src/styles/theme.css'],
      // Code reads as a terminal in both site themes. A light syntax theme on warm paper
      // washes out to near-invisible, and switching themes mid-scroll is worse than
      // committing to one.
      expressiveCode: {
        themes: ['github-dark'],
        styleOverrides: {
          borderRadius: '3px',
          borderColor: 'transparent',
          codeFontFamily: 'var(--decoy-mono)',
        },
      },
      components: {
        // The two loudest Starlight tells: its header lockup and its theme dropdown.
        Header: './src/components/Header.astro',
        PageTitle: './src/components/PageTitle.astro',
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/NerdMeNot/decoy' },
      ],
      editLink: { baseUrl: 'https://github.com/NerdMeNot/decoy/edit/main/website/' },
      lastUpdated: true,
      pagination: true,
      head: [
        { tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' } },
        {
          tag: 'link',
          attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true },
        },
        {
          tag: 'link',
          attrs: {
            rel: 'stylesheet',
            href:
              'https://fonts.googleapis.com/css2?' +
              'family=Public+Sans:wght@400;500;600;700&' +
              'family=IBM+Plex+Mono:wght@400;500;600&display=swap',
          },
        },
        // Applied before first paint, so a reader who collapsed the sidebar does not
        // watch it flash open on every navigation.
        {
          tag: 'script',
          content:
            "try{var d=document.documentElement.dataset;" +
            "if(localStorage.getItem('decoy:sidebar'))d.sidebar='collapsed';" +
            "if(localStorage.getItem('decoy:toc'))d.toc='collapsed'}catch(e){}",
        },
      ],
      sidebar: [
        {
          label: 'Start',
          items: [
            { slug: 'start/install' },
            { slug: 'start/quick-start' },
            { slug: 'start/cheatsheet' },
          ],
        },
        {
          label: 'Guides',
          items: [
            { slug: 'guides/forges' },
            { slug: 'guides/testing' },
            { slug: 'guides/seeding-a-database' },
            { slug: 'guides/locales' },
            { slug: 'guides/seeds' },
          ],
        },
        {
          // Autogenerated so a new namespace appears without touching this file.
          label: 'Generators',
          // Twenty-nine entries, which is most of the sidebar if left open. Starlight
          // expands whichever group holds the current page, so landing on a namespace
          // still shows its siblings.
          collapsed: true,
          items: [{ autogenerate: { directory: 'api' } }],
        },
        {
          label: 'Reference',
          items: [
            { slug: 'reference/locale-matrix' },
            { slug: 'reference/sources' },
            { slug: 'reference/cli' },
            { slug: 'reference/corpus-format' },
            { slug: 'reference/design-notes' },
          ],
        },
      ],
    }),
  ],
})
